<?php

namespace Database\Seeders;

use App\Models\Causes;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CausesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Causes::updateOrCreate(['name'=> 'DISTOMATOSIS']);
        Causes::updateOrCreate(['name'=> 'TELANGECTASIA']);
        Causes::updateOrCreate(['name'=> 'De. GRASA ']);
        Causes::updateOrCreate(['name'=> 'TUMORES']);
        Causes::updateOrCreate(['name'=> 'ABSCESOS']);
        Causes::updateOrCreate(['name'=> 'CIRROSIS']);
        Causes::updateOrCreate(['name'=> 'CONGESTIÓN']);
        Causes::updateOrCreate(['name'=> 'HIDRONEFROSIS']);
        Causes::updateOrCreate(['name'=> 'PARÁSITOS']);
        Causes::updateOrCreate(['name'=> 'QUISTES PARASITARIOS']);
        Causes::updateOrCreate(['name'=> 'PERITONITIS']);
        Causes::updateOrCreate(['name'=> 'TRAUMATISMOS']);
        Causes::updateOrCreate(['name'=> 'HEMATOMAS']);
        Causes::updateOrCreate(['name'=> 'CROMATOSIS']);
        Causes::updateOrCreate(['name'=> 'MIASIS']);
        Causes::updateOrCreate(['name'=> 'NECROSIS']);
        Causes::updateOrCreate(['name'=> 'ADHERENCIAS']);
        Causes::updateOrCreate(['name'=> 'ENFISEMA']);

        $record = Causes::where('name', 'BRONCO ASPIRACIÓN')->orWhere('name', 'BRONCOASPIRACIÓN')->firstOrNew();
        $record->name = 'BRONCOASPIRACIÓN';
        $record->save();
        
        Causes::updateOrCreate(['name'=> 'BRONCO ASPIRACIÓN']);
        Causes::updateOrCreate(['name'=> 'HEMORRÁGICO']);
        Causes::updateOrCreate(['name'=> 'DESHIDRATACION']);
        Causes::updateOrCreate(['name'=> 'PRODUCCIÓN LÁCTICA']);
        Causes::updateOrCreate(['name'=> 'MATERIA ORGÁNICA']);
        Causes::updateOrCreate(['name'=> 'CONTENIDO RUMINAL']);
        Causes::updateOrCreate(['name'=> 'MATERIA FECAL']);

        Causes::updateOrCreate(['name' => 'DISTOMATOSIS']);
        Causes::updateOrCreate(['name' => 'TELANGECTASIA']);
        Causes::updateOrCreate(['name' => 'De. GRASA ']);
        Causes::updateOrCreate(['name' => 'TUMORES']);
        Causes::updateOrCreate(['name' => 'ABSCESOS']);
        Causes::updateOrCreate(['name' => 'CIRROSIS']);
        Causes::updateOrCreate(['name' => 'CONGESTIÓN']);
        Causes::updateOrCreate(['name' => 'HIDRONEFROSIS']);
        Causes::updateOrCreate(['name' => 'PARÁSITOS']);
        Causes::updateOrCreate(['name' => 'QUISTES PARASITARIOS']);
        Causes::updateOrCreate(['name' => 'PERITONITIS']);
        Causes::updateOrCreate(['name' => 'TRAUMATISMOS']);
        Causes::updateOrCreate(['name' => 'HEMATOMAS']);
        Causes::updateOrCreate(['name' => 'CROMATOSIS']);
        Causes::updateOrCreate(['name' => 'MIASIS']);
        Causes::updateOrCreate(['name' => 'NECROSIS']);
        Causes::updateOrCreate(['name' => 'ADHERENCIAS']);
        Causes::updateOrCreate(['name' => 'ENFISEMA']);
        Causes::updateOrCreate(['name' => 'BRONCOASPIRACIÓN']);
        Causes::updateOrCreate(['name' => 'HEMORRÁGICO']);
        Causes::updateOrCreate(['name' => 'DESHIDRATACION']);
        Causes::updateOrCreate(['name' => 'PRODUCCIÓN LÁCTICA']);
        Causes::updateOrCreate(['name' => 'MATERIA ORGÁNICA']);
        Causes::updateOrCreate(['name' => 'CONTENIDO RUMINAL']);
        Causes::updateOrCreate(['name' => 'MATERIA FECAL']);
        Causes::updateOrCreate(['name' => 'CAQUEXIA']);
        Causes::updateOrCreate(['name' => 'MUERTE EN CORRAL']);
        Causes::updateOrCreate(['name' => 'MUERTE EN TRANSPORTE']);
        Causes::updateOrCreate(['name' => 'ANIMAL FEBRIL']);
        Causes::updateOrCreate(['name' => 'INCOORDINACIÓN MOTORA']);
        Causes::updateOrCreate(['name' => 'HIPOTERMIA']);
        Causes::updateOrCreate(['name' => 'ESTADO AGONICO']);
        Causes::updateOrCreate(['name' => 'AUSENCIA DE COAGULACION']);
        Causes::updateOrCreate(['name' => 'HERIDAS']);
        Causes::updateOrCreate(['name' => 'FUNGOSIS']);
        Causes::updateOrCreate(['name' => 'QUEMADURAS']);
        Causes::updateOrCreate(['name' => 'ANASARCA']);
        Causes::updateOrCreate(['name' => 'ECTOPARASITOS']);
        Causes::updateOrCreate(['name' => 'SARNA']);
        Causes::updateOrCreate(['name' => 'DERMATITIS']);
        Causes::updateOrCreate(['name' => 'ERITEMA']);
        Causes::updateOrCreate(['name' => 'PAPILOMATOSIS']);
        Causes::updateOrCreate(['name' => 'CONGESTION ']);
        Causes::updateOrCreate(['name' => 'PANADIZO']);
        Causes::updateOrCreate(['name' => 'FLEMÓN']);
        Causes::updateOrCreate(['name' => 'ABSCESO']);
        Causes::updateOrCreate(['name' => 'ARTRITIS']);
        Causes::updateOrCreate(['name' => 'NECROBACILOSIS']);
        Causes::updateOrCreate(['name' => 'PODODERMATITIS']);
        Causes::updateOrCreate(['name' => 'ACTINOMICOSIS']);
        Causes::updateOrCreate(['name' => 'EPITELIOMA DEL OJO']);
        Causes::updateOrCreate(['name' => 'SINUSITIS']);
        Causes::updateOrCreate(['name' => 'LENGUA CON AFTAS']);
        Causes::updateOrCreate(['name' => 'ADENOPATIA']);
        Causes::updateOrCreate(['name' => 'ABSESOS']);
        Causes::updateOrCreate(['name' => 'EDEMA']);
        Causes::updateOrCreate(['name' => 'INFILTRACION GANGLIONAR']);
        Causes::updateOrCreate(['name' => 'CONGESTION']);
        Causes::updateOrCreate(['name' => 'REGURGITACION']);
        Causes::updateOrCreate(['name' => 'NEUMONIA ']);
        Causes::updateOrCreate(['name' => 'BRONQUITIS']);
        Causes::updateOrCreate(['name' => 'ATELECTASIA']);
        Causes::updateOrCreate(['name' => 'MELANOSIS']);
        Causes::updateOrCreate(['name' => 'SARCOSPORIDIOSIS']);
        Causes::updateOrCreate(['name' => 'HIDROPERICARDIO']);
        Causes::updateOrCreate(['name' => 'PERICARDITIS']);
        Causes::updateOrCreate(['name' => 'ENDOCARDITIS']);
        Causes::updateOrCreate(['name' => 'CONGESTION']);
        Causes::updateOrCreate(['name' => 'HEPATOMEGALIA']);
        Causes::updateOrCreate(['name' => 'QUISTES']);
        Causes::updateOrCreate(['name' => 'TELANGIECTASIA']);
        Causes::updateOrCreate(['name' => 'FIBROSIS']);
        Causes::updateOrCreate(['name' => 'ESPLENOMEGALIA']);
        Causes::updateOrCreate(['name' => 'CONGESTION']);
        Causes::updateOrCreate(['name' => 'COMPLETAS']);
        Causes::updateOrCreate(['name' => 'GASTRITIS CONGESTIVA']);
        Causes::updateOrCreate(['name' => 'GASTRITIS NECROTICA']);
        Causes::updateOrCreate(['name' => 'MALPOSICION Y NECROSIS']);
        Causes::updateOrCreate(['name' => 'IMPREGNACION URINARIA']);
        Causes::updateOrCreate(['name' => 'ATROFIA']);
        Causes::updateOrCreate(['name' => 'ENTERITIS']);
        Causes::updateOrCreate(['name' => 'ENTERITIS HEMORRAGICA']);
        Causes::updateOrCreate(['name' => 'QUISTES']);
        Causes::updateOrCreate(['name' => 'PROLAPSO RECTAL']);
        Causes::updateOrCreate(['name' => 'NECROSIS']);
        Causes::updateOrCreate(['name' => 'UTERO']);
        Causes::updateOrCreate(['name' => 'METRITIS']);
        Causes::updateOrCreate(['name' => 'FETOS']);
        Causes::updateOrCreate(['name' => 'PROLAPSO VAGINAL']);
        Causes::updateOrCreate(['name' => 'PLACENTA RETENIDA']);
        Causes::updateOrCreate(['name' => 'UTERO POR TORSION']);
        Causes::updateOrCreate(['name' => 'VAGINITIS']);
        Causes::updateOrCreate(['name' => 'MASTITIS']);
        Causes::updateOrCreate(['name' => 'EDEMA']);
        Causes::updateOrCreate(['name' => 'NECROSIS']);
        Causes::updateOrCreate(['name' => 'EPIDIMITIS']);
        Causes::updateOrCreate(['name' => 'CONGESTION']);
        Causes::updateOrCreate(['name' => 'ORQUITIS']);
        Causes::updateOrCreate(['name' => 'BALANITIS']);
        Causes::updateOrCreate(['name' => 'QUISTES']);
        Causes::updateOrCreate(['name' => 'CISTITIS']);
        Causes::updateOrCreate(['name' => 'NEFRITIS']);
        Causes::updateOrCreate(['name' => 'OSTEONECROSIS']);
        Causes::updateOrCreate(['name' => 'PLEURITIS SEPTICA']);
        Causes::updateOrCreate(['name' => 'CALCIFICACION']);
        Causes::updateOrCreate(['name' => 'PLEURITIS']);
        Causes::updateOrCreate(['name' => 'UREMIA']);
        Causes::updateOrCreate(['name' => 'DESCOMPOSICION']);
        Causes::updateOrCreate(['name' => 'ADENOPATIA']);
        Causes::updateOrCreate(['name' => 'HIDATIDIOSIS']);
        Causes::updateOrCreate(['name' => 'ENCEFALITIS EQUINA']);
        Causes::updateOrCreate(['name' => 'CLOSTRIDIOSIS']);
        Causes::updateOrCreate(['name' => 'TRIQUINOSIS']);
        Causes::updateOrCreate(['name' => 'TOXOPLASMOSIS']);
        Causes::updateOrCreate(['name' => 'ICTERICIA']);
        Causes::updateOrCreate(['name' => 'ACETONEMIA']);
        Causes::updateOrCreate(['name' => 'PARESIA PUERPERAL']);
        Causes::updateOrCreate(['name' => 'OTROS']);
        Causes::updateOrCreate(['name' => 'FRACTURA']);
        Causes::updateOrCreate(['name' => 'OSTEOMIELITIS']);
        Causes::updateOrCreate(['name' => 'ARTRITIS']);
        Causes::updateOrCreate(['name' => 'ARTRITIS SUPURATIVA']);
        Causes::updateOrCreate(['name' => 'TENDINITIS']);
        Causes::updateOrCreate(['name' => 'INFECCION AGUDA']);
        Causes::updateOrCreate(['name' => 'MIOSITIS']);
        Causes::updateOrCreate(['name' => 'MIASIS']);
        Causes::updateOrCreate(['name' => 'ESTRONGILOSIS']);
        Causes::updateOrCreate(['name' => 'MIASIS']);
        Causes::updateOrCreate(['name' => 'OTROS']);
        Causes::updateOrCreate(['name' => 'TETANO']);
        Causes::updateOrCreate(['name' => 'BOTULISMO']);
        Causes::updateOrCreate(['name' => 'ACTINOMICOSIS']);
        Causes::updateOrCreate(['name' => 'PARATUBERCULOSIS']);
        Causes::updateOrCreate(['name' => 'OTROS']);
        Causes::updateOrCreate(['name' => 'ESTOMATITIS VESICULAR']);
        Causes::updateOrCreate(['name' => 'VIRUELA BOVINA']);
        Causes::updateOrCreate(['name' => 'FIEBRE CATARRAL']);
        Causes::updateOrCreate(['name' => 'RINOTRAQUEITIS']);
        Causes::updateOrCreate(['name' => 'DIARREA VIRAL']);
        Causes::updateOrCreate(['name' => 'LEUCOSIS']);
        Causes::updateOrCreate(['name' => 'AFTOSA']);
        Causes::updateOrCreate(['name' => 'BRUCELOSIS']);
        Causes::updateOrCreate(['name' => 'RABIA SILV. BOVINA']);
        Causes::updateOrCreate(['name' => 'TUBERCULOSIS']);
        Causes::updateOrCreate(['name' => 'CISTICERCOSIS']);
        Causes::updateOrCreate(['name' => 'EN VISCERA BLANCA']);
        Causes::updateOrCreate(['name' => 'EN VISCERA ROJA']);
        Causes::updateOrCreate(['name' => 'EN HUESOS']);
        Causes::updateOrCreate(['name' => 'MELANOMA']);

    }
}
