<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

    /**
     * Huila
     */
    City::updateOrCreate(['name' => 'Agrado', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Altamira', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Garzón', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Gigante', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Guadalupe', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Pital', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Suaza', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Tarqui', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Aipe', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Algeciras', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Baraya', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Campoalegre', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Colombia', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Hobo', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Iquira', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Neiva', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Palermo', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Rivera', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Santa María', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Tello', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Teruel', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Villavieja', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Yaguará', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'La Argentina', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'La Plata', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Nátaga', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Paicol', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Tesalia', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Acevedo', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Elías', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Isnos', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Oporapa', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Palestina', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Pitalito', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Saladoblanco', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'San Agustín', 'id_department' => 18]);
    City::updateOrCreate(['name' => 'Timaná', 'id_department' => 18]);
    /**
     * Amazonas
     */
    // City::updateOrCreate(['name' => 'El Encanto', 'id_department' => 1],);
    // City::updateOrCreate(['name' => 'La Chorrera', 'id_department' => 1],);
    // City::updateOrCreate(['name' => 'La Pedrera', 'id_department' => 1],);
    // City::updateOrCreate(['name' => 'La Victoria', 'id_department' => 1],);
    // City::updateOrCreate(['name' => 'Leticia', 'id_department' => 1],);
    // City::updateOrCreate(['name' => 'Mirití-Paraná', 'id_department' => 1],);
    // City::updateOrCreate(['name' => 'Puerto Alegría', 'id_department' => 1],);
    // City::updateOrCreate(['name' => 'Puerto Arica', 'id_department' => 1],);
    // City::updateOrCreate(['name' => 'Puerto Nariño', 'id_department' => 1],);
    // City::updateOrCreate(['name' => 'Puerto Santander', 'id_department' => 1],);
    // City::updateOrCreate(['name' => 'Tarapacá', 'id_department' => 1],);
    // /**
    //  * Antioquia
    //  */
    // City::updateOrCreate(['name' => 'Cáceres', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Caucasia', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'El Bagre', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Nechí', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Tarazá', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Zaragoza', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Caracolí', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Maceo', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Puerto Berrio', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Puerto Nare', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Puerto Triunfo', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Yondó', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Amalfi', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Anorí', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Cisneros', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Remedios', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'San Roque', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Santo Domingo', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Segovia', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Vegachí', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Yalí', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Yolombó', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Angostura', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Belmira', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Briceño', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Campamento', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Carolina', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Don Matias', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Entrerrios', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Gómez Plata', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Guadalupe', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Ituango', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'San Andrés', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'San José De La Montaña', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'San Pedro', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Santa Rosa De Osos', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Toledo', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Valdivia', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Yarumal', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Abriaquí', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Anza', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Armenia', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Buriticá', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Cañasgordas', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Dabeiba', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Ebéjico', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Frontino', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Giraldo', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Heliconia', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Liborina', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Olaya', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Peque', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Sabanalarga', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'San Jerónimo', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Santafé De Antioquia', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Sopetran', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Uramita', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Abejorral', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Alejandría', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Argelia', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Carmen De Viboral', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Cocorná', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Concepción', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Granada', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Guarne', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Guatape', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'La Ceja', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'La Unión', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Marinilla', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Nariño', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Peñol', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Retiro', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Rionegro', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'San Carlos', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'San Francisco', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'San Luis', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'San Rafael', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'San Vicente', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Santuario', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Sonson', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Amaga', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Andes', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Angelopolis', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Betania', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Betulia', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Caicedo', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Caramanta', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Ciudad Bolívar', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Concordia', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Fredonia', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Hispania', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Jardín', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Jericó', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'La Pintada', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Montebello', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Pueblorrico', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Salgar', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Santa Barbara', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Támesis', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Tarso', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Titiribí', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Urrao', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Valparaiso', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Venecia', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Apartadó', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Arboletes', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Carepa', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Chigorodó', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Murindó', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Mutata', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Necoclí', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'San Juan De Uraba', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'San Pedro De Uraba', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Turbo', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Vigía Del Fuerte', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Barbosa', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Bello', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Caldas', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Copacabana', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Envigado', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Girardota', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Itagui', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'La Estrella', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Medellín', 'id_department' => 2]);
    // City::updateOrCreate(['name' => 'Sabaneta', 'id_department' => 2]);
    // /**
    //  * Arauca
    //  */
    // City::updateOrCreate(['name' => 'Arauca', 'id_department' => 3]);
    // City::updateOrCreate(['name' => 'Arauquita', 'id_department' => 3]);
    // City::updateOrCreate(['name' => 'Cravo Norte', 'id_department' => 3]);
    // City::updateOrCreate(['name' => 'Fortul', 'id_department' => 3]);
    // City::updateOrCreate(['name' => 'Puerto Rondón', 'id_department' => 3]);
    // City::updateOrCreate(['name' => 'Saravena', 'id_department' => 3]);
    // City::updateOrCreate(['name' => 'Tame', 'id_department' => 3]);
    // /**
    //  * Atlántico
    //  */
    // City::updateOrCreate(['name' => 'Barranquilla', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Galapa', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Malambo', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Puerto Colombia', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Soledad', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Campo De La Cruz', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Candelaria', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Luruaco', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Manati', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Repelon', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Santa Lucia', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Suan', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Baranoa', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Palmar De Varela', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Polonuevo', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Ponedera', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Sabanagrande', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Sabanalarga', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Santo Tomas', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Juan De Acosta', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Piojó', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Tubara', 'id_department' => 4]);
    // City::updateOrCreate(['name' => 'Usiacuri', 'id_department' => 4]);
    // /**
    //  * Bogota D.C.
    //  */
    // City::updateOrCreate(['name' => 'Bogota D.C.', 'id_department' => 5]);
    // /**
    //  * Bolívar
    //  */
    // City::updateOrCreate(['name' => 'Cicuco', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Hatillo De Loba', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Margarita', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Mompós', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'San Fernando', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Talaigua Nuevo', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Arjona', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Arroyohondo', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Calamar', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Cartagena', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Clemencia', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Mahates', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'San Cristobal', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'San Estanislao', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Santa Catalina', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Santa Rosa De Lima', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Soplaviento', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Turbaco', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Turbana', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Villanueva', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Altos Del Rosario', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Barranco De Loba', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'El Peñon', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Regidor', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Río Viejo', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'San Martin De Loba', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Arenal', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Cantagallo', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Morales', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'San Pablo', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Santa Rosa Del Sur', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Simití', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Achí', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Magangué', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Montecristo', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Pinillos', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'San Jacinto Del Cauca', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Tiquisio', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Carmen De Bolívar', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Córdoba', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'El Guamo', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'María La Baja', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'San Jacinto', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'San Juan Nepomuceno', 'id_department' => 6]);
    // City::updateOrCreate(['name' => 'Zambrano', 'id_department' => 6]);
    // /**
    //  * Boyacá
    //  */
    // City::updateOrCreate(['name' => 'Chíquiza', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Chivatá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Cómbita', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Cucaita', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Motavita', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Oicatá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Samacá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Siachoque', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Sora', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Soracá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Sotaquirá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Toca', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Tunja', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Tuta', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Ventaquemada', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Chiscas', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Cubará', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'El Cocuy', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'El Espino', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Guacamayas', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Güicán', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Panqueba', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Labranzagrande', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Pajarito', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Paya', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Pisba', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Berbeo', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Campohermoso', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Miraflores', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Páez', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'San Eduardo', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Zetaquira', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Boyacá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Ciénega', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Jenesano', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Nuevo Colón', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Ramiriquí', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Rondón', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Tibaná', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Turmequé', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Umbita', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Viracachá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Chinavita', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Garagoa', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Macanal', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Pachavita', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'San Luis De Gaceno', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Santa María', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Boavita', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Covarachía', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'La Uvita', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'San Mateo', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Sativanorte', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Sativasur', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Soatá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Susacón', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Tipacoque', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Briceño', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Buenavista', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Caldas', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Chiquinquirá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Coper', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'La Victoria', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Maripí', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Muzo', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Otanche', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Pauna', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Puerto Boyaca', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Quípama', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Saboyá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'San Miguel De Sema', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'San Pablo Borbur', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Tununguá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Almeida', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Chivor', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Guateque', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Guayatá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'La Capilla', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Somondoco', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Sutatenza', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Tenza', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Arcabuco', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Chitaraque', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Gachantivá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Moniquirá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Ráquira', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Sáchica', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'San José De Pare', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Santa Sofía', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Santana', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Sutamarchán', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Tinjacá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Togüí', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Villa De Leyva', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Aquitania', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Cuítiva', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Firavitoba', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Gameza', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Iza', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Mongua', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Monguí', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Nobsa', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Pesca', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Sogamoso', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Tibasosa', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Tópaga', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Tota', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Belén', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Busbanzá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Cerinza', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Corrales', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Duitama', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Floresta', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Paipa', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'San Rosa Viterbo', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Tutazá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Betéitiva', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Chita', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Jericó', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Paz De Río', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Socha', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Socotá', 'id_department' => 7]);
    // City::updateOrCreate(['name' => 'Tasco', 'id_department' => 7]);
    // /**
    //  * Caldas
    //  */
    // City::updateOrCreate(['name' => 'Filadelfia', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'La Merced', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Marmato', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Riosucio', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Supía', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Manzanares', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Marquetalia', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Marulanda', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Pensilvania', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Anserma', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Belalcázar', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Risaralda', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'San José', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Viterbo', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Chinchina', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Manizales', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Neira', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Palestina', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Villamaria', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Aguadas', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Aranzazu', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Pácora', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Salamina', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'La Dorada', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Norcasia', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Samaná', 'id_department' => 8]);
    // City::updateOrCreate(['name' => 'Victoria', 'id_department' => 8]);
    // /**
    //  * Caquetá
    //  */
    // City::updateOrCreate(['name' => 'Albania', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'Belén De Los Andaquies', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'Cartagena Del Chairá', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'Currillo', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'El Doncello', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'El Paujil', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'Florencia', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'La Montañita', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'Milan', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'Morelia', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'Puerto Rico', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'San Jose Del Fragua', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'San Vicente Del Caguán', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'Solano', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'Solita', 'id_department' => 9]);
    // City::updateOrCreate(['name' => 'Valparaiso', 'id_department' => 9]);
    // /**
    //  * Casanare
    //  */
    // City::updateOrCreate(['name' => 'Aguazul', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Chameza', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Hato Corozal', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'La Salina', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Maní', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Monterrey', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Nunchía', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Orocué', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Paz De Ariporo', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Pore', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Recetor', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Sabanalarga', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Sácama', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'San Luis De Palenque', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Támara', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Tauramena', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Trinidad', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Villanueva', 'id_department' => 10]);
    // City::updateOrCreate(['name' => 'Yopal', 'id_department' => 10]);
    // /**
    //  * Cauca
    //  */
    // City::updateOrCreate(['name' => 'Cajibío', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'El Tambo', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'La Sierra', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Morales', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Piendamo', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Popayán', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Rosas', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Sotara', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Timbio', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Buenos Aires', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Caloto', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Corinto', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Miranda', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Padilla', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Puerto Tejada', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Santander De Quilichao', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Suarez', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Villa Rica', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Guapi', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Lopez', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Timbiqui', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Caldono', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Inzá', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Jambalo', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Paez', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Purace', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Silvia', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Toribio', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Totoro', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Almaguer', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Argelia', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Balboa', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Bolívar', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Florencia', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'La Vega', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Mercaderes', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Patia', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Piamonte', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'San Sebastian', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Santa Rosa', 'id_department' => 11]);
    // City::updateOrCreate(['name' => 'Sucre', 'id_department' => 11]);
    // /**
    //  * Cesar
    //  */
    // City::updateOrCreate(['name' => 'Becerril', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Chimichagua', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Chiriguana', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Curumaní', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'La Jagua De Ibirico', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Pailitas', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Tamalameque', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Astrea', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Bosconia', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'El Copey', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'El Paso', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Agustín Codazzi', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'La Paz', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Manaure', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Pueblo Bello', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'San Diego', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Valledupar', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Aguachica', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Gamarra', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'González', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'La Gloria', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Pelaya', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'Río De Oro', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'San Alberto', 'id_department' => 12]);
    // City::updateOrCreate(['name' => 'San Martín', 'id_department' => 12]);
    // /**
    //  * Chocó
    //  */
    // City::updateOrCreate(['name' => 'Atrato', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Bagadó', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Bojaya', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'El Carmen De Atrato', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Lloró', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Medio Atrato', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Quibdó', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Rio Quito', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Acandí', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Belén De Bajira', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Carmén Del Darién', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Riosucio', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Unguía', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Bahía Solano', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Juradó', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Nuquí', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Alto Baudó', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Bajo Baudó', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'El Litoral Del San Juan', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Medio Baudó', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Canton De San Pablo', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Certegui', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Condoto', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Itsmina', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Medio San Juan', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Nóvita', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Río Frío', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'San José Del Palmar', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Sipí', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Tadó', 'id_department' => 13]);
    // City::updateOrCreate(['name' => 'Union Panamericana', 'id_department' => 13]);
    // /**
    //  * Córdoba
    //  */
    // City::updateOrCreate(['name' => 'Tierralta', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Valencia', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Chimá', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Cotorra', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Lorica', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Momil', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Purísima', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Montería', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Canalete', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Los Córdobas', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Moñitos', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Puerto Escondido', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'San Antero', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'San Bernardo Del Viento', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Chinú', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Sahagún', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'San Andrés Sotavento', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Ayapel', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Buenavista', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'La Apartada', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Montelíbano', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Planeta Rica', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Pueblo Nuevo', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Puerto Libertador', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Cereté', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'Ciénaga De Oro', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'San Carlos', 'id_department' => 14]);
    // City::updateOrCreate(['name' => 'San Pelayo', 'id_department' => 14]);
    // /**
    //  * Cundinamarca
    //  */
    // City::updateOrCreate(['name' => 'Chocontá', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Macheta', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Manta', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Sesquilé', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Suesca', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Tibirita', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Villapinzón', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Agua De Dios', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Girardot', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Guataquí', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Jerusalén', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Nariño', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Nilo', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Ricaurte', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Tocaima', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Caparrapí', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Guaduas', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Puerto Salgar', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Albán', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'La Peña', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'La Vega', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Nimaima', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Nocaima', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Quebradanegra', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'San Francisco', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Sasaima', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Supatá', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Útica', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Vergara', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Villeta', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Gachala', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Gacheta', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Gama', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Guasca', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Guatavita', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Junín', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'La Calera', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Ubalá', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Beltrán', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Bituima', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Chaguaní', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Guayabal De Siquima', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Puli', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'San Juan De Río Seco', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Vianí', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Medina', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Paratebueno', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Caqueza', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Chipaque', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Choachí', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Fomeque', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Fosca', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Guayabetal', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Gutiérrez', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Quetame', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Ubaque', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Une', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'El Peñón', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'La Palma', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Pacho', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Paime', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'San Cayetano', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Topaipi', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Villagomez', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Yacopí', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Cajicá', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Chía', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Cogua', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Gachancipá', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Nemocon', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Sopó', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Tabio', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Tocancipá', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Zipaquirá', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Bojacá', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Cota', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'El Rosal', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Facatativá', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Funza', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Madrid', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Mosquera', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Subachoque', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Tenjo', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Zipacon', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Sibaté', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Soacha', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Arbeláez', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Cabrera', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Fusagasugá', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Granada', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Pandi', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Pasca', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'San Bernardo', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Silvania', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Tibacuy', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Venecia', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Anapoima', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Anolaima', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Apulo', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Cachipay', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'El Colegio', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'La Mesa', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Quipile', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'San Antonio De Tequendama', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Tena', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Viotá', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Carmen De Carupa', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Cucunubá', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Fúquene', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Guachetá', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Lenguazaque', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Simijaca', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Susa', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Sutatausa', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Tausa', 'id_department' => 15]);
    // City::updateOrCreate(['name' => 'Ubate', 'id_department' => 15]);
    // /**
    //  * Guainía
    //  */
    // City::updateOrCreate(['name' => 'Barranco Mina', 'id_department' => 16]);
    // City::updateOrCreate(['name' => 'Cacahual', 'id_department' => 16]);
    // City::updateOrCreate(['name' => 'Inírida', 'id_department' => 16]);
    // City::updateOrCreate(['name' => 'La Guadalupe', 'id_department' => 16]);
    // City::updateOrCreate(['name' => 'Mapiripan', 'id_department' => 16]);
    // City::updateOrCreate(['name' => 'Morichal', 'id_department' => 16]);
    // City::updateOrCreate(['name' => 'Pana Pana', 'id_department' => 16]);
    // City::updateOrCreate(['name' => 'Puerto Colombia', 'id_department' => 16]);
    // City::updateOrCreate(['name' => 'San Felipe', 'id_department' => 16]);
    // /**
    //  * Guaviare
    //  */
    // City::updateOrCreate(['name' => 'Calamar', 'id_department' => 17]);
    // City::updateOrCreate(['name' => 'El Retorno', 'id_department' => 17]);
    // City::updateOrCreate(['name' => 'Miraflores', 'id_department' => 17]);
    // City::updateOrCreate(['name' => 'San José Del Guaviare', 'id_department' => 17]);
    // /**
    //  * La Guajira
    //  */
    // City::updateOrCreate(['name' => 'Albania', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'Dibulla', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'Maicao', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'Manaure', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'Riohacha', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'Uribia', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'Barrancas', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'Distraccion', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'El Molino', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'Fonseca', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'Hatonuevo', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'La Jagua Del Pilar', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'San Juan Del Cesar', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'Urumita', 'id_department' => 19]);
    // City::updateOrCreate(['name' => 'Villanueva', 'id_department' => 19]);
    // /**
    //  * Magdalena
    //  */
    // City::updateOrCreate(['name' => 'Ariguaní', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Chibolo', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Nueva Granada', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Plato', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Sabanas De San Angel', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Tenerife', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Algarrobo', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Aracataca', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Ciénaga', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'El Reten', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Fundacion', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Pueblo Viejo', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Zona Bananera', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Cerro San Antonio', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Concordia', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'El Piñon', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Pedraza', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Pivijay', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Remolino', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Salamina', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Sitionuevo', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Zapayan', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Santa Marta', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'El Banco', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Guamal', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Pijiño Del Carmen', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'San Sebastian De Buenavista', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'San Zenon', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Santa Ana', 'id_department' => 20]);
    // City::updateOrCreate(['name' => 'Santa Barbara De Pinto', 'id_department' => 20]);
    // /**
    //  * Meta
    //  */
    // City::updateOrCreate(['name' => 'El Castillo', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'El Dorado', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Fuente De Oro', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Granada', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'La Macarena', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'La Uribe', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Lejanías', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Mapiripan', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Mesetas', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Puerto Concordia', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Puerto Lleras', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Puerto Rico', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'San Juan De Arama', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Vista Hermosa', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Villavicencio', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Acacias', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Barranca De Upia', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Castilla La Nueva', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Cumaral', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'El Calvario', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Guamal', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Restrepo', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'San Carlos Guaroa', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'San Juanito', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'San Luis De Cubarral', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'San Martín', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Cabuyaro', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Puerto Gaitán', 'id_department' => 21]);
    // City::updateOrCreate(['name' => 'Puerto Lopez', 'id_department' => 21]);
    //     /**
    //  * Nariño
    //  */
    // City::updateOrCreate(['name' => 'Chachagui', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Consaca', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'El Peñol', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'El Tambo', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'La Florida', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Nariño', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Pasto', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Sandoná', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Tangua', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Yacuanquer', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Ancuya', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Guaitarilla', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'La Llanada', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Linares', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Los Andes', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Mallama', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Ospina', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Providencia', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Ricaurte', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Samaniego', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Santa Cruz', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Sapuyes', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Tuquerres', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Barbacoas', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'El Charco', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Francisco Pizarro', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'La Tola', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Magui', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Mosquera', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Olaya Herrera', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Roberto Payan', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Santa Barbara', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Tumaco', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Alban', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Arboleda', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Belen', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Buesaco', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Colon', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Cumbitara', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'El Rosario', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'El Tablon De Gomez', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'La Cruz', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'La Union', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Leiva', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Policarpa', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'San Bernardo', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'San Lorenzo', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'San Pablo', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'San Pedro De Cartago', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Taminango', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Aldana', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Contadero', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Córdoba', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Cuaspud', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Cumbal', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Funes', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Guachucal', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Gualmatan', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Iles', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Imues', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Ipiales', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Potosí', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Puerres', 'id_department' => 22]);
    // City::updateOrCreate(['name' => 'Pupiales', 'id_department' => 22]);
    // /**
    //  * Norte de Santander
    //  */
    // City::updateOrCreate(['name' => 'Arboledas', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Cucutilla', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Gramalote', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Lourdes', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Salazar', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Santiago', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Villa Caro', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Bucarasica', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'El Tarra', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Sardinata', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Tibú', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Abrego', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Cachirá', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Convención', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'El Carmen', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Hacarí', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'La Esperanza', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'La Playa', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Ocaña', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'San Calixto', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Teorama', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Cúcuta', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'El Zulia', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Los Patios', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Puerto Santander', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'San Cayetano', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Villa Del Rosario', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Cácota', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Chitagá', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Mutiscua', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Pamplona', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Pamplonita', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Silos', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Bochalema', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Chinácota', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Durania', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Herrán', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Labateca', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Ragonvalia', 'id_department' => 23]);
    // City::updateOrCreate(['name' => 'Toledo', 'id_department' => 23]);
    // /**
    //  * Putumayo
    //  */
    // City::updateOrCreate(['name' => 'Colón', 'id_department' => 24]);
    // City::updateOrCreate(['name' => 'Mocoa', 'id_department' => 24]);
    // City::updateOrCreate(['name' => 'Orito', 'id_department' => 24]);
    // City::updateOrCreate(['name' => 'Puerto Asis', 'id_department' => 24]);
    // City::updateOrCreate(['name' => 'Puerto Caicedo', 'id_department' => 24]);
    // City::updateOrCreate(['name' => 'Puerto Guzman', 'id_department' => 24]);
    // City::updateOrCreate(['name' => 'Puerto Leguizamo', 'id_department' => 24]);
    // City::updateOrCreate(['name' => 'San Francisco', 'id_department' => 24]);
    // City::updateOrCreate(['name' => 'San Miguel', 'id_department' => 24]);
    // City::updateOrCreate(['name' => 'Santiago', 'id_department' => 24]);
    // City::updateOrCreate(['name' => 'Sibundoy', 'id_department' => 24]);
    // City::updateOrCreate(['name' => 'Valle Del Guamuez', 'id_department' => 24]);
    // City::updateOrCreate(['name' => 'Villa Garzon', 'id_department' => 24]);
    // /**
    //  * Quindío
    //  */
    // City::updateOrCreate(['name' => 'Armenia', 'id_department' => 25]);
    // City::updateOrCreate(['name' => 'Buenavista', 'id_department' => 25]);
    // City::updateOrCreate(['name' => 'Calarca', 'id_department' => 25]);
    // City::updateOrCreate(['name' => 'Cordoba', 'id_department' => 25]);
    // City::updateOrCreate(['name' => 'Genova', 'id_department' => 25]);
    // City::updateOrCreate(['name' => 'Pijao', 'id_department' => 25]);
    // City::updateOrCreate(['name' => 'Filandia', 'id_department' => 25]);
    // City::updateOrCreate(['name' => 'Salento', 'id_department' => 25]);
    // City::updateOrCreate(['name' => 'Circasia', 'id_department' => 25]);
    // City::updateOrCreate(['name' => 'La Tebaida', 'id_department' => 25]);
    // City::updateOrCreate(['name' => 'Montengro', 'id_department' => 25]);
    // City::updateOrCreate(['name' => 'Quimbaya', 'id_department' => 25]);
    // /**
    //  * Risaralda
    //  */
    // City::updateOrCreate(['name' => 'Dosquebradas', 'id_department' => 26]);
    // City::updateOrCreate(['name' => 'La Virginia', 'id_department' => 26]);
    // City::updateOrCreate(['name' => 'Marsella', 'id_department' => 26]);
    // City::updateOrCreate(['name' => 'Pereira', 'id_department' => 26]);
    // City::updateOrCreate(['name' => 'Santa Rosa De Cabal', 'id_department' => 26]);
    // City::updateOrCreate(['name' => 'Apía', 'id_department' => 26]);
    // City::updateOrCreate(['name' => 'Balboa', 'id_department' => 26]);
    // City::updateOrCreate(['name' => 'Belén De Umbría', 'id_department' => 26]);
    // City::updateOrCreate(['name' => 'Guática', 'id_department' => 26]);
    // City::updateOrCreate(['name' => 'La Celia', 'id_department' => 26]);
    // City::updateOrCreate(['name' => 'Quinchia', 'id_department' => 26]);
    // City::updateOrCreate(['name' => 'Santuario', 'id_department' => 26]);
    // City::updateOrCreate(['name' => 'Mistrató', 'id_department' => 26]);
    // City::updateOrCreate(['name' => 'Pueblo Rico', 'id_department' => 26]);
    // /**
    //  * San Andrés y Providencia
    //  */
    // City::updateOrCreate(['name' => 'Providencia Y Santa Catalina', 'id_department' => 27]);
    // City::updateOrCreate(['name' => 'San Andres', 'id_department' => 27]);
    // /**
    //  * Santander
    //  */
    // City::updateOrCreate(['name' => 'Chima', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Confines', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Contratación', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'El Guacamayo', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Galán', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Gambita', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Guadalupe', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Guapotá', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Hato', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Oiba', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Palmar', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Palmas Del Socorro', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Santa Helena Del Opón', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Simacota', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Socorro', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Suaita', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Capitanejo', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Carcasí', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Cepitá', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Cerrito', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Concepción', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Enciso', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Guaca', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Macaravita', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Málaga', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Molagavita', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'San Andrés', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'San José De Miranda', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'San Miguel', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Aratoca', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Barichara', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Cabrera', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Charalá', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Coromoro', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Curití', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Encino', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Jordán', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Mogotes', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Ocamonte', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Onzaga', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Páramo', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Pinchote', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'San Gil', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'San Joaquín', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Valle De San José', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Villanueva', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Barrancabermeja', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Betulia', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'El Carmen De Chucurí', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Puerto Wilches', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Sabana De Torres', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'San Vicente De Chucurí', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Zapatoca', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Bucaramanga', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'California', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Charta', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'El Playón', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Floridablanca', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Girón', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Lebríja', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Los Santos', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Matanza', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Piedecuesta', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Rionegro', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Santa Bárbara', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Surata', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Tona', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Vetas', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Aguada', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Albania', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Barbosa', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Bolívar', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Chipatá', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Cimitarra', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'El Peñón', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Florián', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Guavatá', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Guepsa', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Jesús María', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'La Belleza', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'La Paz', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Landázuri', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Puente Nacional', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Puerto Parra', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'San Benito', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Sucre', 'id_department' => 28]);
    // City::updateOrCreate(['name' => 'Vélez', 'id_department' => 28]);
    // /**
    //  * Sucre
    //  */
    // City::updateOrCreate(['name' => 'Guaranda', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Majagual', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Sucre', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Chalán', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Coloso', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Morroa', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Ovejas', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Sincelejo', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Coveñas', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Palmito', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'San Onofre', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Santiago De Tolú', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Tolú Viejo', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Buenavista', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Corozal', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'El Roble', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Galeras', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Los Palmitos', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Sampués', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'San Juan Betulia', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'San Pedro', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Sincé', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'Caimito', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'La Unión', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'San Benito Abad', 'id_department' => 29]);
    // City::updateOrCreate(['name' => 'San Marcos', 'id_department' => 29]);
    // /**
    //  * Tolima
    //  */
    // City::updateOrCreate(['name' => 'Ambalema', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Armero', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Falan', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Fresno', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Honda', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Mariquita', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Palocabildo', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Carmen De Apicalá', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Cunday', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Icononzo', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Melgar', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Villarrica', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Ataco', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Chaparral', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Coyaima', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Natagaima', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Ortega', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Planadas', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Rioblanco', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Roncesvalles', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'San Antonio', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Alvarado', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Anzoátegui', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Cajamarca', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Coello', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Espinal', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Flandes', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Ibague', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Piedras', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Rovira', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'San Luis', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Valle De San Juan', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Alpujarra', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Dolores', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Guamo', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Prado', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Purificación', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Saldaña', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Suárez', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Casabianca', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Herveo', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Lerida', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Libano', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Murillo', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Santa Isabel', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Venadillo', 'id_department' => 30]);
    // City::updateOrCreate(['name' => 'Villahermosa', 'id_department' => 30]);

    // /**
    //  * Valle del Cauca
    //  */
    // City::updateOrCreate(['name' => 'Andalucía', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Buga', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Bugalagrande', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Calima', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'El Cerrito', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Ginebra', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Guacarí', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Restrepo', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Riofrio', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'San Pedro', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Trujillo', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Tuluá', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Yotoco', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Alcala', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Ansermanuevo', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Argelia', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Bolívar', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Cartago', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'El Águila', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'El Cairo', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'El Dovio', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'La Unión', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'La Victoria', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Obando', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Roldanillo', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Toro', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Ulloa', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Versalles', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Zarzal', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Buenaventura', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Caicedonia', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Sevilla', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Cali', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Candelaria', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Dagua', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Florida', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Jamundí', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'La Cumbre', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Palmira', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Pradera', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Vijes', 'id_department' => 31]);
    // City::updateOrCreate(['name' => 'Yumbo', 'id_department' => 31]);
    // /**
    //  * Vaupés
    //  */
    // City::updateOrCreate(['name' => 'Caruru', 'id_department' => 32]);
    // City::updateOrCreate(['name' => 'Mitú', 'id_department' => 32]);
    // City::updateOrCreate(['name' => 'Pacoa', 'id_department' => 32]);
    // City::updateOrCreate(['name' => 'Papunahua', 'id_department' => 32]);
    // City::updateOrCreate(['name' => 'Taraira', 'id_department' => 32]);
    // City::updateOrCreate(['name' => 'Yavaraté', 'id_department' => 32]);
    // /**
    //  * Vichada
    //  */
    // City::updateOrCreate(['name' => 'Cumaribo', 'id_department' => 33]);
    // City::updateOrCreate(['name' => 'La Primavera', 'id_department' => 33]);
    // City::updateOrCreate(['name' => 'Puerto Carreño', 'id_department' => 33]);
    // City::updateOrCreate(['name' => 'Santa Rosalía', 'id_department' => 33]);
    }
}
